FROM kaggle/python

WORKDIR /home
RUN git clone https://83a0ca722df6a0647f1ea08fb5df089fbc0ee328:x-oauth-basic@github.com/flowlight0/QuoraQuestionPairs.git

WORKDIR /home/QuoraQuestionPairs
RUN pip install -r required_packages.txt

    


